### ISSUE TITLE
Run the program

### ISSUE THREAD

**Issue by anasmuhamad98** [kornelius-s/Java-Threads#1]
Hi, I tried to run your program in eclipse and I got this output. But I think the output should not be like this so is there anything I should do before run the program?

**All the visitors reached the exit

Threads created: 5 starting at the Site[Entrance]

Occupancy status for each room (should all be zero, but the exit site):
Site Whales Exhibition Room final occupancy: 0
Site VenomKillerAndCureRoom final occupancy: 0**

**Comment by s1ddhi** [comment]
Hi,

That is the intended output and there are no prerequisites before running the program.

As reported, the simulation (as run in that instance) resulted in all visitors exiting the museum where each individual room has no leftover/stuck visitors as they are 0. I do realise that the comment in the parenthesis, "should all be zero, but the exit site" might be interpreted as an issue, but taking a look at the code itself, one can see that it is always outputted.

I hope this helps.
